/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;


import controller.ControllerCadastroAreaCompartilhada;
import controller.ControllerCadastroCustoNivel1;
import controller.ControllerCadastroCustoNivel2;
import controller.ControllerCadastroEdificio;
import controller.ControllerCadastroFornecedor;
import controller.ControllerCadastroProprietario;
import controller.ControllerCadastroSindicoProfissional;
import controller.ControllerCadastroUnidade;
import controller.ControllerCadastroUnidadeCondomino;


/**
 *
 * @author aluno
 */
public class TelaMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaMenuPrincipal
     */
    public TelaMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemEdificio = new javax.swing.JMenuItem();
        jMenuItemUnidade = new javax.swing.JMenuItem();
        jMenuItemUnidadeCondominio = new javax.swing.JMenuItem();
        jMenuItemAreaCompartilhada = new javax.swing.JMenuItem();
        jMenuItemAreaEdificio = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemProprietario = new javax.swing.JMenuItem();
        jMenuItemFornecedor = new javax.swing.JMenuItem();
        jMenuItemSindico = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItemCustoNivel1 = new javax.swing.JMenuItem();
        jMenuItemCustoNivel2 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        setResizable(false);

        jMenuBar1.setBackground(new java.awt.Color(153, 153, 255));

        jMenu2.setText("Cadastros");

        jMenuItemEdificio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Company.png"))); // NOI18N
        jMenuItemEdificio.setText("Edifício");
        jMenuItemEdificio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEdificioActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemEdificio);

        jMenuItemUnidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Home.png"))); // NOI18N
        jMenuItemUnidade.setText("Unidade");
        jMenuItemUnidade.setActionCommand("Unidade Hab.");
        jMenuItemUnidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUnidadeActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemUnidade);

        jMenuItemUnidadeCondominio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Clipboard.png"))); // NOI18N
        jMenuItemUnidadeCondominio.setText("Unidade X Condomínio");
        jMenuItemUnidadeCondominio.setToolTipText("");
        jMenuItemUnidadeCondominio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUnidadeCondominioActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemUnidadeCondominio);

        jMenuItemAreaCompartilhada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Blue pin.png"))); // NOI18N
        jMenuItemAreaCompartilhada.setText("Área Compartilhada");
        jMenuItemAreaCompartilhada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAreaCompartilhadaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemAreaCompartilhada);

        jMenuItemAreaEdificio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Clipboard.png"))); // NOI18N
        jMenuItemAreaEdificio.setText("Área X Edifício");
        jMenuItemAreaEdificio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAreaEdificioActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemAreaEdificio);
        jMenu2.add(jSeparator1);

        jMenuItemProprietario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Boss.png"))); // NOI18N
        jMenuItemProprietario.setText("Proprietário");
        jMenuItemProprietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProprietarioActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemProprietario);

        jMenuItemFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Delivery.png"))); // NOI18N
        jMenuItemFornecedor.setText("Fornecedor");
        jMenuItemFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFornecedorActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemFornecedor);

        jMenuItemSindico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/People.png"))); // NOI18N
        jMenuItemSindico.setText("Síndico Profissional");
        jMenuItemSindico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSindicoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemSindico);
        jMenu2.add(jSeparator3);

        jMenuItemCustoNivel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Euro.png"))); // NOI18N
        jMenuItemCustoNivel1.setText("Centro de Custo 1");
        jMenuItemCustoNivel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCustoNivel1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemCustoNivel1);

        jMenuItemCustoNivel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Euro.png"))); // NOI18N
        jMenuItemCustoNivel2.setText("Centro de Custo 2");
        jMenuItemCustoNivel2.setToolTipText("");
        jMenuItemCustoNivel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCustoNivel2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemCustoNivel2);
        jMenu2.add(jSeparator2);

        jMenuItemSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Exit.png"))); // NOI18N
        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemSair);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Movimentos");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Relatórios");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Ajuda");

        jMenuItem1.setText("Sobre");
        jMenu5.add(jMenuItem1);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemEdificioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEdificioActionPerformed

        TelaCadastroEdificio_1 telaCadastroEdificio = new TelaCadastroEdificio_1(null, true);
        ControllerCadastroEdificio controllerCadastroEdificio = new ControllerCadastroEdificio(telaCadastroEdificio);
        telaCadastroEdificio.setVisible(true);

    }//GEN-LAST:event_jMenuItemEdificioActionPerformed

    private void jMenuItemProprietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProprietarioActionPerformed
        TelaCadastroProprietario telaCadastroProprietario = new TelaCadastroProprietario(null, true);
        ControllerCadastroProprietario controllerCadastroProprietario = new ControllerCadastroProprietario(telaCadastroProprietario);
        telaCadastroProprietario.setVisible(true);
    }//GEN-LAST:event_jMenuItemProprietarioActionPerformed

    private void jMenuItemUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUnidadeActionPerformed
        TelaCadastroUnidade telaCadastroUnidade = new TelaCadastroUnidade(null, true);
        ControllerCadastroUnidade controllerCadastroUnidade = new ControllerCadastroUnidade(telaCadastroUnidade);
        telaCadastroUnidade.setVisible(true);
    }//GEN-LAST:event_jMenuItemUnidadeActionPerformed

    private void jMenuItemFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFornecedorActionPerformed
        TelaCadastroFornecedor telaCadastroFornecedor = new TelaCadastroFornecedor(null, true);
        ControllerCadastroFornecedor controllerCadastroFornecedor = new ControllerCadastroFornecedor(telaCadastroFornecedor);
        telaCadastroFornecedor.setVisible(true);
    }//GEN-LAST:event_jMenuItemFornecedorActionPerformed

    private void jMenuItemSindicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSindicoActionPerformed
        TelaCadastroSindicoProfissional telaCadastroSindicoProfissional = new TelaCadastroSindicoProfissional(null, true);
        ControllerCadastroSindicoProfissional controllerCadastroSindicoProfissional = new ControllerCadastroSindicoProfissional(telaCadastroSindicoProfissional);
        telaCadastroSindicoProfissional.setVisible(true);
    }//GEN-LAST:event_jMenuItemSindicoActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemAreaCompartilhadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAreaCompartilhadaActionPerformed
        TelaCadastroAreaCompartilhada telaCadastroAreaCompartilhada = new TelaCadastroAreaCompartilhada(null, true);
        ControllerCadastroAreaCompartilhada controllerCadastroAreaCompartilhada = new ControllerCadastroAreaCompartilhada(telaCadastroAreaCompartilhada);
        telaCadastroAreaCompartilhada.setVisible(true);
    }//GEN-LAST:event_jMenuItemAreaCompartilhadaActionPerformed

    private void jMenuItemCustoNivel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCustoNivel2ActionPerformed
        TelaCadastroCustoNivel2 telaCadastroCustoNivel2 = new TelaCadastroCustoNivel2(null, true);
        ControllerCadastroCustoNivel2 controllerCadastroCustoNivel2 = new ControllerCadastroCustoNivel2(telaCadastroCustoNivel2);
        telaCadastroCustoNivel2.setVisible(true);
    }//GEN-LAST:event_jMenuItemCustoNivel2ActionPerformed

    private void jMenuItemCustoNivel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCustoNivel1ActionPerformed
        TelaCadastroCustoNivel1 telaCadastroCustoNivel1 = new TelaCadastroCustoNivel1(null, true);
        ControllerCadastroCustoNivel1 controllerCadastroCustoNivel1 = new ControllerCadastroCustoNivel1(telaCadastroCustoNivel1);
        telaCadastroCustoNivel1.setVisible(true);
    }//GEN-LAST:event_jMenuItemCustoNivel1ActionPerformed

    private void jMenuItemUnidadeCondominioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUnidadeCondominioActionPerformed
        TelaCadastroUnidadeCondomino telaCadastroUnidadeCondominio = new TelaCadastroUnidadeCondomino(null, true);
        ControllerCadastroUnidadeCondomino ControllerCadastroUnidadeCondomino = new ControllerCadastroUnidadeCondomino(telaCadastroUnidadeCondominio);
        telaCadastroUnidadeCondominio.setVisible(true);
    }//GEN-LAST:event_jMenuItemUnidadeCondominioActionPerformed

    private void jMenuItemAreaEdificioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAreaEdificioActionPerformed
      
    }//GEN-LAST:event_jMenuItemAreaEdificioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemAreaCompartilhada;
    private javax.swing.JMenuItem jMenuItemAreaEdificio;
    private javax.swing.JMenuItem jMenuItemCustoNivel1;
    private javax.swing.JMenuItem jMenuItemCustoNivel2;
    private javax.swing.JMenuItem jMenuItemEdificio;
    private javax.swing.JMenuItem jMenuItemFornecedor;
    private javax.swing.JMenuItem jMenuItemProprietario;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemSindico;
    private javax.swing.JMenuItem jMenuItemUnidade;
    private javax.swing.JMenuItem jMenuItemUnidadeCondominio;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
